### ISSUE TITLE
Add a search feature

### ISSUE THREAD

**Issue by ldmpub** [bekoeppel/droidplane#7]
Hi,

I hope you're doing well?

I'm a great fan of Freeplane (both for pro and personnal uses) and DroidPlane is the best MindMap app which runs under Android to display my maps. Many thanks for this app!

Even if I guess app is in "standby", I suggest (only one) improvment which will change my life => adding a text search feature.

Waiting for your feedback,

**Comment by ldmpub** [comment]
Hi @bekoeppel,

I'm happy to see you are still "alive around Freeplane" 👍 (see https://github.com/freeplane/freeplane/issues/223 ).

Can you tell me:
1. Have you planned to improve DroidPlane? (or this project is abandoned from your point of view ?)
2. Have you find an alternative app to view and perform basic tasks (like searching 😂) on Freeplane MindMaps under Android?

Eager to get your answer, thanks,

**Comment by bekoeppel** [comment]
Hey @ldmpub, 

thanks for the message and happy to hear from a fellow mindmapper :smiley:. Yes, I am using Freeplane and DroidPlane every day, and will make sure DroidPlane works on the latest Android versions. However, due to my current work commitment (Founder & CTO at [Locatee](https://locatee.com/)), I am not actively working on new features in DroidPlane at the moment. 

I would be happy for somebody else to step up and develop new features like the search functionality. 

Benedikt

**Comment by ldmpub** [comment]
Is it coming? See https://github.com/bekoeppel/droidplane/pull/10

**Comment by ldmpub** [comment]
Implemented search works fine for me (used in DroidPlane beta), many thanks 👏.
